/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentLikeCreateNestedManyWithoutUsersInput } from "./CommentLikeCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { CommentCreateNestedManyWithoutUsersInput } from "./CommentCreateNestedManyWithoutUsersInput";
import { CommunityCreateNestedManyWithoutUsersInput } from "./CommunityCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserFeedCreateNestedManyWithoutUsersInput } from "./UserFeedCreateNestedManyWithoutUsersInput";
import { EnumUserUserType } from "./EnumUserUserType";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommentLikeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CommentLikeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CommentLikeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  commentLikes?: CommentLikeCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CommunityCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CommunityCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CommunityCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  communities?: CommunityCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserFeedCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserFeedCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserFeedCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userFeeds?: UserFeedCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: true,
    enum: EnumUserUserType,
  })
  @IsEnum(EnumUserUserType)
  @Field(() => EnumUserUserType)
  userType!: "Lessee" | "Lessor";
}

export { UserCreateInput as UserCreateInput };
