/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { EnumEscrowDepositStatus } from "./EnumEscrowDepositStatus";
import { StringFilter } from "../../util/StringFilter";
import { RentalWhereUniqueInput } from "../../rental/base/RentalWhereUniqueInput";

@InputType()
class EscrowWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  blockchainHash?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  deletedAt?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  depositAmount?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumEscrowDepositStatus,
  })
  @IsEnum(EnumEscrowDepositStatus)
  @IsOptional()
  @Field(() => EnumEscrowDepositStatus, {
    nullable: true,
  })
  depositStatus?: "Active" | "Settled" | "Reversed";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => RentalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RentalWhereUniqueInput)
  @IsOptional()
  @Field(() => RentalWhereUniqueInput, {
    nullable: true,
  })
  rentalId?: RentalWhereUniqueInput;
}

export { EscrowWhereInput as EscrowWhereInput };
