/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentUpdateManyWithoutCommunityFeedsInput } from "./CommentUpdateManyWithoutCommunityFeedsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CommunityWhereUniqueInput } from "../../community/base/CommunityWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { FeedLikeUpdateManyWithoutCommunityFeedsInput } from "./FeedLikeUpdateManyWithoutCommunityFeedsInput";
import { MediaUpdateManyWithoutCommunityFeedsInput } from "./MediaUpdateManyWithoutCommunityFeedsInput";

@InputType()
class CommunityFeedUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutCommunityFeedsInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutCommunityFeedsInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutCommunityFeedsInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutCommunityFeedsInput;

  @ApiProperty({
    required: false,
    type: () => CommunityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CommunityWhereUniqueInput)
  @IsOptional()
  @Field(() => CommunityWhereUniqueInput, {
    nullable: true,
  })
  community?: CommunityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  creator?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FeedLikeUpdateManyWithoutCommunityFeedsInput,
  })
  @ValidateNested()
  @Type(() => FeedLikeUpdateManyWithoutCommunityFeedsInput)
  @IsOptional()
  @Field(() => FeedLikeUpdateManyWithoutCommunityFeedsInput, {
    nullable: true,
  })
  feedLikes?: FeedLikeUpdateManyWithoutCommunityFeedsInput;

  @ApiProperty({
    required: false,
    type: () => MediaUpdateManyWithoutCommunityFeedsInput,
  })
  @ValidateNested()
  @Type(() => MediaUpdateManyWithoutCommunityFeedsInput)
  @IsOptional()
  @Field(() => MediaUpdateManyWithoutCommunityFeedsInput, {
    nullable: true,
  })
  medias?: MediaUpdateManyWithoutCommunityFeedsInput;
}

export { CommunityFeedUpdateInput as CommunityFeedUpdateInput };
