/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CommunityFeed,
  Comment,
  Community,
  User,
} from "@prisma/client";

export class CommunityFeedServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CommunityFeedCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFeedCountArgs>
  ): Promise<number> {
    return this.prisma.communityFeed.count(args);
  }

  async findMany<T extends Prisma.CommunityFeedFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFeedFindManyArgs>
  ): Promise<CommunityFeed[]> {
    return this.prisma.communityFeed.findMany(args);
  }
  async findOne<T extends Prisma.CommunityFeedFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFeedFindUniqueArgs>
  ): Promise<CommunityFeed | null> {
    return this.prisma.communityFeed.findUnique(args);
  }
  async create<T extends Prisma.CommunityFeedCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFeedCreateArgs>
  ): Promise<CommunityFeed> {
    return this.prisma.communityFeed.create<T>(args);
  }
  async update<T extends Prisma.CommunityFeedUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFeedUpdateArgs>
  ): Promise<CommunityFeed> {
    return this.prisma.communityFeed.update<T>(args);
  }
  async delete<T extends Prisma.CommunityFeedDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFeedDeleteArgs>
  ): Promise<CommunityFeed> {
    return this.prisma.communityFeed.delete(args);
  }

  async findComments(
    parentId: string,
    args: Prisma.CommentFindManyArgs
  ): Promise<Comment[]> {
    return this.prisma.communityFeed
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .comments(args);
  }

  async getCommunity(parentId: string): Promise<Community | null> {
    return this.prisma.communityFeed
      .findUnique({
        where: { id: parentId },
      })
      .community();
  }

  async getCreator(parentId: string): Promise<User | null> {
    return this.prisma.communityFeed
      .findUnique({
        where: { id: parentId },
      })
      .creator();
  }
}
