/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Comment, // @ts-ignore
  CommentLike, // @ts-ignore
  User, // @ts-ignore
  UserFeed,
} from "@prisma/client";

export class CommentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CommentCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentCountArgs>
  ): Promise<number> {
    return this.prisma.comment.count(args);
  }

  async comments<T extends Prisma.CommentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentFindManyArgs>
  ): Promise<Comment[]> {
    return this.prisma.comment.findMany(args);
  }
  async comment<T extends Prisma.CommentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentFindUniqueArgs>
  ): Promise<Comment | null> {
    return this.prisma.comment.findUnique(args);
  }
  async createComment<T extends Prisma.CommentCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentCreateArgs>
  ): Promise<Comment> {
    return this.prisma.comment.create<T>(args);
  }
  async updateComment<T extends Prisma.CommentUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentUpdateArgs>
  ): Promise<Comment> {
    return this.prisma.comment.update<T>(args);
  }
  async deleteComment<T extends Prisma.CommentDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentDeleteArgs>
  ): Promise<Comment> {
    return this.prisma.comment.delete(args);
  }

  async findCommentLikes(
    parentId: string,
    args: Prisma.CommentLikeFindManyArgs
  ): Promise<CommentLike[]> {
    return this.prisma.comment
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .commentLikes(args);
  }

  async getCreator(parentId: string): Promise<User | null> {
    return this.prisma.comment
      .findUnique({
        where: { id: parentId },
      })
      .creator();
  }

  async getUserFeed(parentId: string): Promise<UserFeed | null> {
    return this.prisma.comment
      .findUnique({
        where: { id: parentId },
      })
      .userFeed();
  }
}
