/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CarImageCreateNestedManyWithoutCarsInput } from "./CarImageCreateNestedManyWithoutCarsInput";
import { ValidateNested, IsOptional, IsDate, IsString } from "class-validator";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { RentalCreateNestedManyWithoutCarsInput } from "./RentalCreateNestedManyWithoutCarsInput";

@InputType()
class CarCreateInput {
  @ApiProperty({
    required: false,
    type: () => CarImageCreateNestedManyWithoutCarsInput,
  })
  @ValidateNested()
  @Type(() => CarImageCreateNestedManyWithoutCarsInput)
  @IsOptional()
  @Field(() => CarImageCreateNestedManyWithoutCarsInput, {
    nullable: true,
  })
  carImages?: CarImageCreateNestedManyWithoutCarsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  deletedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput)
  lessorId!: UserWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  make!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  model!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  registrationInfo!: string;

  @ApiProperty({
    required: false,
    type: () => RentalCreateNestedManyWithoutCarsInput,
  })
  @ValidateNested()
  @Type(() => RentalCreateNestedManyWithoutCarsInput)
  @IsOptional()
  @Field(() => RentalCreateNestedManyWithoutCarsInput, {
    nullable: true,
  })
  rentals?: RentalCreateNestedManyWithoutCarsInput;
}

export { CarCreateInput as CarCreateInput };
