/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Public } from "../../decorators/public.decorator";
import { CreateRentalArgs } from "./CreateRentalArgs";
import { UpdateRentalArgs } from "./UpdateRentalArgs";
import { DeleteRentalArgs } from "./DeleteRentalArgs";
import { RentalCountArgs } from "./RentalCountArgs";
import { RentalFindManyArgs } from "./RentalFindManyArgs";
import { RentalFindUniqueArgs } from "./RentalFindUniqueArgs";
import { Rental } from "./Rental";
import { Car } from "../../car/base/Car";
import { User } from "../../user/base/User";
import { Plan } from "../../plan/base/Plan";
import { RentalService } from "../rental.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Rental)
export class RentalResolverBase {
  constructor(
    protected readonly service: RentalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Rental",
    action: "read",
    possession: "any",
  })
  async _rentalsMeta(
    @graphql.Args() args: RentalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Rental])
  @nestAccessControl.UseRoles({
    resource: "Rental",
    action: "read",
    possession: "any",
  })
  async rentals(@graphql.Args() args: RentalFindManyArgs): Promise<Rental[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Rental, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rental",
    action: "read",
    possession: "own",
  })
  async rental(
    @graphql.Args() args: RentalFindUniqueArgs
  ): Promise<Rental | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Rental)
  @nestAccessControl.UseRoles({
    resource: "Rental",
    action: "create",
    possession: "any",
  })
  async createRental(@graphql.Args() args: CreateRentalArgs): Promise<Rental> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        carId: {
          connect: args.data.carId,
        },

        lesseeId: {
          connect: args.data.lesseeId,
        },

        planId: {
          connect: args.data.planId,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Rental)
  @nestAccessControl.UseRoles({
    resource: "Rental",
    action: "update",
    possession: "any",
  })
  async updateRental(
    @graphql.Args() args: UpdateRentalArgs
  ): Promise<Rental | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          carId: {
            connect: args.data.carId,
          },

          lesseeId: {
            connect: args.data.lesseeId,
          },

          planId: {
            connect: args.data.planId,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Rental)
  @nestAccessControl.UseRoles({
    resource: "Rental",
    action: "delete",
    possession: "any",
  })
  async deleteRental(
    @graphql.Args() args: DeleteRentalArgs
  ): Promise<Rental | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Car, {
    nullable: true,
    name: "carId",
  })
  @nestAccessControl.UseRoles({
    resource: "Car",
    action: "read",
    possession: "any",
  })
  async resolveFieldCarId(
    @graphql.Parent() parent: Rental
  ): Promise<Car | null> {
    const result = await this.service.getCarId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "lesseeId",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async resolveFieldLesseeId(
    @graphql.Parent() parent: Rental
  ): Promise<User | null> {
    const result = await this.service.getLesseeId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.ResolveField(() => Plan, {
    nullable: true,
    name: "planId",
  })
  async resolveFieldPlanId(
    @graphql.Parent() parent: Rental
  ): Promise<Plan | null> {
    const result = await this.service.getPlanId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
